server:
  port: 8080

factservice:
  host: %fact-service-url%

fibservice:
  host: %fib-service-url%

spring:
  application:
    name: compute-service
  sleuth:
    sampler:
      probability: 1
    web:
      skipPattern:
        (^cleanup.*|.+favicon.*)
